### ISSUE TITLE
Incluir explicación del proyecto

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/contratosmenores#19]
Ahora que el proyecto acoge los datos de más ciudades es necesario dar un poco de contexto y explicar los por qué y cómos.

Probablemente sea una sección específica en la web ¿home?, o un desplegable en el header.

Eso también hace replantearse qué incluiría esa hipotética "landing page".

**Comment by Krabii** [comment]
[Información](https://frama.link/DVHG9YnE) en la pagina de la comunidad de Madrid pone que los contratos menores deben ser inferiores a 50.000 euros en caso de obras o a 18.000 euros en el resto de contratos (sin IVA). Igual es una cosa que tenemos que comentar en el gráfico o en palabras. Creo que es una cosa bastante visible en los contratos menores donde hay muchos contratos que rondan los 20.000 y muchos que rondan los 60.000 , entre estos dos valores hay menos actividad. 

EDIT : Acabo de ver que hay las lineas horizontales que describen exactamente eso!!

**Comment by numeroteca** [comment]
He creado una página de inicio del proyecto 957b3213ac ya disponible en la nueva ubicación de la web: https://lab.montera34.com/contratosmenores/home.html
Hará falta explicar qué son los contratos menores, @electroduende21 ¿te animas?

**Comment by numeroteca** [comment]
Gracias @electroduende21. Ya he pasado tu aportación b12130ce7c48cdb a la rama principal.
