### ISSUE TITLE
Filtrado sobre filtrado

### ISSUE THREAD

**Issue by electroduende21** [numeroteca/contratosmenores#2]
Podría haber la opción a que se generen filtros que se apliquen encima de otros? 
(empresa Y servicio)
Actualmente sólo puedes visualizar el resultado de seleccionar un botón

**Comment by numeroteca** [comment]
Sí, sería una buena opción. Voy a ver cómo de fácil es añadirla.

**Comment by Krabii** [comment]
La implementación de los filtros esta hecha. Se puede seleccionar uno de cada (empresa, centro y servicio). De momento solo en valencia 2015. Faltan detalles como

1. Que hacer con el texto descriptivo que aparece en el gráfico. Una idea es que tenga los filtros pero puede resultar un texto largo.
2. El tema de la opacidad. En principio las barras tienen una opacidad 0.4 y al seleccionar se intensifica 0.8 Ahora con los filtros múltiples al de-seleccionar uno de los filtros, algunas barras vuelven a 0.4 y otras se quedan con 0.8

**Comment by electroduende21** [comment]
Muy buenas Krabii,

Bienvenido al proyecto!!!!
Disculpa que no os saludara antes. Entre el mundo activista, y que todavía
ando en procesos de mudanza, a caballo entre 2 ciudades siempre voy falto
de horas.

He hecho una prueba entrando en
http://numeroteca.org/contratosmenores/index.html
(Valencia 2015).

1. Veo importante monitorizar los filtros aplicados, y más cuando se
superponen. La cantidad es importante, el texto podría ser algo más tipo
abreviatura.
    Otra opción sería recalcar los botones que se han pulsado con un color.

2. La opacidad se me escapa.

**Comment by numeroteca** [comment]
Post sobre el tema: https://smalldata.noblogs.org/post/2017/06/08/filtrar-selecciones-en-d3-js/

> - 1 Que hacer con el texto descriptivo que aparece en el gráfico. Una idea es que tenga los filtros pero puede resultar un texto largo.

Podríamos pensar en una estructura de tres columnas (en tres div encima del gráfico) para que sea responsive. Cada columna llevaría el filtro activo.

> - 2 El tema de la opacidad. En principio las barras tienen una opacidad 0.4 y al seleccionar se intensifica 0.8 Ahora con los filtros múltiples al de-seleccionar uno de los filtros, algunas barras vuelven a 0.4 y otras se quedan con 0.8

En vez de primero ocultar todas con hidden como está ahora
```
svg.selectAll('svg .bar').style("visibility","hidden");
svg.selectAll('svg .bar'+ filtersText).style("opacity",activeopacity).style("visibility","visible"); //selects contracts that match the dni in its class
```
¿podríamos intentar cambiar la opacidad de todas  y luego solamente cambiar la opacidad de las activas?

**Comment by electroduende21** [comment]
Muy buenas, os escribo un par de lineas para ir comentando el avance.

A nivel técnico,
el filtrado sobre filtrado está muy bien, y queda muy limpio el reflejar
qué filtro se ha aplicado. Bravo.
Echo en falta mantener visible la suma de la cantidad total de los
contratos que se visualizan.

A nivel activista,
1. Para ganar en difusión, sería interesante desarrollarlo para que sea
embebido.
2. También me parece importante ampliar al usuario a todos los proveedores,
no sólo los que se ven. Para ello, quizá la mejor opción sería hacer una
lista desplegable con todas las opciones...
3. Algo que siempre viene bien es poder buscar con una caja de texto en las
descripciones de los contratos (muy lolailas a veces)

**Comment by Krabii** [comment]
Hola @electroduende21 ,

gracias por la bienvenida! 
Es verdad falta poner la cantidad y darle un poco de estilo a la descripción. Un borde o algo así.

1. No he probado lo de embebido pero creo que con <iframe> funciona, como se comenta en uno de los issues. El problema igual es que es muy grande, tiene formato de pagina web. Igual te refieres que sea mas compacto para caber bien en otras paginas web.
2. El desplegable es una cosa que comentamos con @numeroteca y voy a empezar a trabajar en ello
3. No me queda claro que tendría esa caja de texto...

**Comment by numeroteca** [comment]
1. Embebido: continuemos la conversación en el hilo correspondiente #13.
2. Va por el buen camino. Tenemos que actualizar el archivo de proveedores para que liste todos, a ver qué tal funciona. Esto es el issue #3.
3. Esto sería que una caja de búsqueda para el tercer filtro que busque en la descripción de los contratos. Se usa cuando ninguna de las palabras de la thinglist te sirve. También descrito en #3. Continuemos allí la conversación.

**Comment by numeroteca** [comment]
A ver qué os parece esta reorganización en tres columnas
![image](https://user-images.githubusercontent.com/1223722/27181060-3500ff96-51d6-11e7-8501-c46d06099e56.png)

**Comment by Krabii** [comment]
Me gusta como ha quedado, pero ya me da ganas de ponerlo todo en desplegables que de un aspecto mas nítido. Por el otro lado los botones que se ¨activan¨ quedan bien a la hora de interactuar, igual merece la pena mantenerlos así.
