### ISSUE TITLE
nombre de centro de Valencia 2015 servicis tecnics

### ISSUE THREAD

**Issue by Krabii** [numeroteca/contratosmenores#21]
en el tsv de centros de Valencia 2015 centroslist_val2015.tsv los Servicios Centrales Tecnicos tienen como palabra enllumentat que corresponde solo a un contrato.

Cuando se elige este centro no aparecen los demas contratos.

cambiando el nombre de centro a sservicis soluciona el problema.

**Comment by numeroteca** [comment]
df48c3b69 fixes this

**Comment by numeroteca** [comment]
Faltaba incluir este centro presupuestario "S.Enllumenat i fonts ornamentals" en el listado.  6e25e8356f
