### ISSUE TITLE
Faltan centros por listar en contratos menores Valencia 2015

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/contratosmenores#23]
A raiz de #21 estoy viendo que faltan muchos otros centros en la visualización de los contratos menores de valencia 2015. En [`centroslist_val2015.tsv`](https://github.com/numeroteca/contratosmenores/blob/master/data/centroslist_val2015.tsv) tenemos 18 pero hay ¡¡45 centros en total!!

Los listo aquí por orden de cantidad total de facturación. Lista realizada con una tabla dinámica (pivot table) con libreoffice:

S.CULTURA FESTIVA	1525020€
S.SERVICIS CENTRALS TECNICS	1242426€
OF.DE PUBLICITAT I ANUNCIS OFICIALS	1130746€
S.JARDINERIA	1128119€
S. EDUCACIO	916980€
S.OBRES D'INFRAESTRUCTURA	810268€
S. TECNOLOGIES DE LA INFORMACIO Y LA COMUNICACIO	665377€
S.BOMBERS,PREVENCIO I INTERVENCIO I PROTEC.CIVIL	613256€
S.PATRIMONI HISTORIC I ARTISTIC	579333€
S.ACCIO CULTURAL	477761€
S.PEDANIES	457552€
S.BENESTAR SOCIAL I INTEGRACIO	452851€
S.JOVENTUD	392430€
S.ESPORTS	380386€
S.OCUPACIO I EMPRENEDORIA	368436€
S.ENLLUMENAT I FONTS ORNAMENTALS	314981€
S.COMERC I ABASTIMENT	296850€
S.PALAU DE LA MUSICA I CONGRESSOS	264543€
S.RECURSOS CULTURALS	251146€
S.PROTOCOL	250245€
S.CIRCULACIO I TRANSPORT I LES SEUES INFRAESTRUCT.	247867€
SUBAREA S.PLANEAM.I GESTIO URBANISTICA	231816€
S.DEVESA-ALBUFERA	226358€
S.DROGODEPENDENCIES	143280€
S.TURISME	135137€
S.CEMENTERIS	103994€
S.POLICIA LOCAL	101521€
S.DESCENTRALITZACIO I PARTICIPACIO CIUTADANA	96476€
S.QUALITAT I AN.MEDIAMB,CONTAM.ACUSTICA I PLATGES	95399€
S.SANITAT	94470€
S.PLATGES	90920€
S.ENERGIES RENOVABLES I CANVI CLIMATIC	86827€
GABINET DE COMUNICACIONS	50628€
S.RELACIONS INTERNACIONALS	47059€
S.CICLE INTEGRAL DEL L'AIGUA	42654€
S.ORGAN SUPORT JGL I REGIDOR SECRETARI	35444€
S.INNOVACIO I SOCIETAT DE LA INFORMACIO	26149€
S.COORD.OBRA VIA PBCA I MANTENIMENT INFRAESTRUCT.	21394€
S.VIVENDA	17846€
S.LLICENCES URBANISTIQUES OBRES D'EDIFICACIO	17497€
SERVICIS CENTRALS	10227€
GABINET D'ALCALDIA	9891€
S.SOCIETAT DE LA INFORMACIO	6000€
S.PATRIMONI	3459€
OFICINA D'ESTADISTICA	805€

Te pongo en copia @electroduende21 para que estés al tanto.

**Comment by electroduende21** [comment]
Cierto. Fue una elección poner los ... 18 que más gastaban para no saturar la visualización.
El problema de poner la lista exahustiva de centros de gasto para mi es el desborde de opciones al usuario.

La web del Ayto de Zaragoza (que estoy husmeando ahora) ofrece listas pop-up de los centros de gasto.
Este problema para mí está enlazado con la opción de una caja de texto que busque en las empresas/centrosdegasto/descripción ofreciendote las opciones posibles en forma de desplegable, o de resultados.

**Comment by numeroteca** [comment]
Bueno, creo que no eran los 18 que más gastaban, pero en cualquier caso sí que hay que pensar cómo poner 45 elementos.
Hablando con @Krabii hemos pensado que sí se pueden poner menús despleglables para las listas de elementos que sean demasiado largas (empresas) y mantener los botones para cuando se pueda. La idea de usar botones creo que facilita interaccionar, más que el desplegable, pero puede ser muy molesto cundo desplazan el gráfico demasiado hacia abajo.

También barajamos la opción de que cuando selecciones una empresa se "coloreen" los centros presupuestarios de los que ha cobrado. También podría hacerse filtrando la lista desplegable y mostrando solo los centros presupuestarios de los que ha cobrado esa empresa.

**Comment by electroduende21** [comment]
Ambas opciones me parecen muy buena idea

**Comment by numeroteca** [comment]
Añade todos los centros: 93dd9ab
