### ISSUE TITLE
¿Cómo mostrar el importe actualizado de barras activas?

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/contratosmenores#24]
¿Se podría extraer con este método (ver commit a01d35d4034c7c) el importe de las barras activas para poder mostrar siempre el total de lo que está activo en el gráfico?

**Comment by Krabii** [comment]
El importe no esta en los elementos del grafico. Pero la informacion que igual se podria aprovechar es el atributo height. Seguramente se calcula segun el importe. Si es una operacion reversible se podria volver a calcular el importe y sumar para todos los elementos seleccionados.

p.ej mira aqui un elemento rect. Yo no veo otro dato que sea facilmente accesible. Sino habria que recorrer cada vez el tsv de datos. Le voy a dar una vuelta.

rect fill="#666666" class="vareasaezfrancisco bar ofde publicitat i anuncis oficials  19893700b  onda valencia tv semana santa  positivo" x="281.01934523809524" width="2.98" y="460.67192307692306" height="4.328076923076935" style="opacity: 0.4; visibility: hidden;"> /rect

**Comment by Krabii** [comment]
Parece que lo que he comentado arriba se puede hacer con el [d3.invert()
](https://github.com/d3/d3-scale/blob/master/README.md#continuous_invert)

Probando en la consola he podido calcular el importe utilizando el valor height de las barras. He ido cotejando con los datos de verdad y esta bien.

Pasare a la implementación.

Habria que ver que en version movil esta igual de correcto.

**Comment by numeroteca** [comment]
En principio los valores que da la consola sí que son correctos, también para móvil. Parece que es una buena solución ¡Está genial!

En principio pensaba que lo de obtener los valores con "invert" no era necesario ya que cada elemento de dibujado con d3 lleva asociado todos los valores de su csv. Entiendo que hay que recurrir a "invert" porque manipulamos las barras representadas y no hay otra forma de detectar los valores que representan ¿correcto?

No he podido reproducir error para SECOPSA.

Ahora queda meter el valor actualizado del importe. Ponlo de momento un en div encima del gráfico y luego le buscamos sitio.

**Comment by Krabii** [comment]
Si esta bien.

Correcto, llevan todos los valores, pero el importe no, o al menos no en numero absoluto, sino en píxeles! con el invert volvemos al importe.

Si selecciono solo la empresa SECOPSA, sin centro ni descripcion, me dice 1324054 pero en las div aparece 1.319.684.00€ una diferencia de 5000 euros.

mira el pantallazo
![contratos_bug](https://user-images.githubusercontent.com/24391214/27329977-fcea0ab8-55b7-11e7-9a93-3e71498652bc.png)

**Comment by numeroteca** [comment]
Encontré el error: hay un contrato de la empresa "SERMA EQUIPAMIENTO URBANO, SL" que tiene asignado equivocadamente el dni de SECOPSA, de ahí el error y la diferencia de 4370€.
`PINTURA MARQUESINAS POSTAS	S.PLATGES	A96062948	SERMA EQUIPAMIENTO URBANO, SL	4370	2015-10-29`

**Comment by numeroteca** [comment]
El importe mostrado tiene múltiples decimales. Lo limitaría a 2 decimales para facilitar lectura.
