### ISSUE TITLE
Cajas de texto y/o lista popup con todos los centros de gasto/suministradores

### ISSUE THREAD

**Issue by electroduende21** [numeroteca/contratosmenores#3]
He visto que hay algo bastante similar que llaman "gastos facturados" en el SW de Civio "Presupuesto Abierto" que acaban de aplicar en el Ayto de Barcelona.

http://ajuntament.barcelona.cat/estrategiaifinances/pressupostobert/es/pagos#view=payee&area=Bienestar+comunitario+(%22servicios+urbanos%22)&description=&date=&payee=Endesa+Energia+Sa+Socunip

Hacen todo..... menos la visualización!!. :-)

**Comment by numeroteca** [comment]
No entiendo bien la propuesta/sugerencia ¿puedes explicarlo mejor?

**Comment by electroduende21** [comment]
Para no limitar al usuario a visualizar sólo las 28 primeras empresas,
sería genial:
a) buscar en una caja la empresa que quieras ver.
b) seleccionarla la empresa de una lista despleglable con todas las disponibles.

En el enlace puedes ver este tipo de selección

**Comment by numeroteca** [comment]
Me parece buena idea. A ver si conseguimos llevarla a cabo.

**Comment by numeroteca** [comment]
Se podría complementar la visualización con tabla con los contratos usando https://datatables.net/

**Comment by numeroteca** [comment]
Un 'autocomplete' en el buscador sería muy útil también para empresas y para centros presupeustarios.

**Comment by numeroteca** [comment]
Resuelto en parte con #23
