### ISSUE TITLE
Simplificar nombre de actividades con openrefine

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/contratosmenores#8]
Valorar si se puede simplificar nombre de actividades con http://openrefine.org/ sin perder datos importantes.
![screenshot-127 0 0 1 3333 2016-10-26 11-54-44](https://cloud.githubusercontent.com/assets/1223722/19721577/24a0dfc8-9b73-11e6-8bba-8b0f77c1e6d1.png)

**Comment by martgnz** [comment]
Hay un campo de fecha aparte no? Y ese campo ya está relleno en p ej Mascletà 03/05/2015?

**Comment by numeroteca** [comment]
Sí, creo que todas las que incluyen fecha habría que simplificarlas. Quedan muchas otras actividades que no tienen la diferencia en la fecha fecha (T1, T2...) pero que se podrían simplificar ¿Qué piensas @electroduende21? ¿puedes echar un ojo con openrefine?

**Comment by martgnz** [comment]
El pbma es que no coinciden porque uno es la fecha de la mascletá y otro la fecha del contrato


Hay un campo de fecha aparte no? Y ese campo ya está relleno en p ej Mascletà 03/05/2015?

—
Martín González
Visual Journalist
https://martingonzalez.net

**Comment by electroduende21** [comment]
Me acabo de bajar openrefine, y los vídeos tienen muy buena pinta.

Yo a mano he pillado algunas "inconsistencias" como las que salen en el vídeo de presentación.
Teniendo en cuenta el DNI del proveedor, hay al menos un contrato duplicado, aparece como:
beneficiario: JUAN CARLOS PEREZ IÑESTA
y tb aparece como
PEREZ IñESTA , JUAN CARLOS  con un contrato idéntico de 870 euros, el 11/06/2015.

Es fundamental limpiar los espacios en blanco después de los números en la columna DNI, para que los agrupemos correctamente, y no por la descripción del proveedor, que es muy variable.

En breve más.

**Comment by numeroteca** [comment]
Bien visto, no terminé de refinar el limpiado ¿te encargas tú @electroduende21?
Creo que los espacios en los DNI estaban limpiados.

Hace falta todavía mejorar: hay 958 empresas y 943 dnis, así que hay que seguir encontrando nombres de empresas con errores.
Usa el archivo actualizado https://github.com/numeroteca/contratosmenores/blob/master/data/data.tsv

**Comment by electroduende21** [comment]
He estado jugando con openrefine y tengo un nuevo fichero y después de unificar proveedores (limpiando los espacios vacíos, con las comas

Ordenando por DNI, resulta que:

Sale un contrato de SERMA EQUIPAMIENTO URBANO. S.L.
con el mismo DNI  que SECOPSA SERVICIOS, S.A.
Para un contrato del 29/10/2015, "PINTURA MARQUESINAS POSTAS     "

Sale un contrato de Ermestel
con el mismo DNI que SPECIALIST COMPUTER CENTRES SOLUTIONS,SL
para un contrato el 2015-11-11, MTTO.SW CITRIX (1-1-16 a 31-12-16)

Sale un contrato con JUAN CARLOS PEREZ IÑESTA
con el mismo DNI que PEREZ IñESTA , JUAN CARLOS
con un contrato idéntico, el 11/06/2015 , "PAGO ARTESANO TALLER   "

**Comment by numeroteca** [comment]
@electroduende21 está trabajando en ello en https://github.com/electroduende21/contratosmenores/tree/Unificando-proveedores
